<?php

namespace Elva\Common\Lib\Enums\Asset\NormalizedDeviceData;

use Elva\Common\Lib\Enums\Traits\Arrayable;

enum DailyAggregateParameter: string
{
    use Arrayable;

    case HC_FLOW_TEMPERATURE_MAX = 'HC_FLOW_TEMPERATURE_MAX';
    case HC_FLOW_TEMPERATURE_SET_POINT_MAX = 'HC_FLOW_TEMPERATURE_SET_POINT_MAX';
    case HC_FLOW_TEMPERATURE_MEAN = 'HC_FLOW_TEMPERATURE_MEAN';

    case HC_ROOM_TEMPERATURE_SET_POINT_MAX = 'HC_ROOM_TEMPERATURE_SET_POINT_MAX';
    case HC_INTERNAL_CIRCULATION_PUMP_OPERATION_TIME_TOTAL = 'HC_INTERNAL_CIRCULATION_PUMP_OPERATION_TIME_TOTAL';
    case HC_RETURN_TEMPERATURE_MEAN = 'HC_RETURN_TEMPERATURE_MEAN';

    case HC_WATER_PRESSURE_MIN = 'HC_WATER_PRESSURE_MIN';
    case HC_WATER_PRESSURE_MAX = 'HC_WATER_PRESSURE_MAX';
    case HC_WATER_PRESSURE_MEAN = 'HC_WATER_PRESSURE_MEAN';

    case COMPRESSOR_CENTRAL_HEATING_STARTS_TOTAL = 'COMPRESSOR_CENTRAL_HEATING_STARTS_TOTAL';
    case COMPRESSOR_CENTRAL_HEATING_OPERATION_TIME_TOTAL = 'COMPRESSOR_CENTRAL_HEATING_OPERATION_TIME_TOTAL';
    case COMPRESSOR_CENTRAL_HEATING_SPEED_MEAN = 'COMPRESSOR_CENTRAL_HEATING_SPEED_MEAN';
    case COMPRESSOR_OPERATION_TIME_TOTAL = 'COMPRESSOR_OPERATION_TIME_TOTAL';

    case COMPRESSOR_ENERGY_CONSUMPTION_TOTAL = 'COMPRESSOR_ENERGY_CONSUMPTION_TOTAL';
    case ENERGY_SUPPLY_TOTAL = 'ENERGY_SUPPLY_TOTAL';
    case ENERGY_SUPPLY_CENTRAL_HEATING_TOTAL = 'ENERGY_SUPPLY_CENTRAL_HEATING_TOTAL';
    case ENERGY_SUPPLY_DOMESTIC_HOT_WATER_TOTAL = 'ENERGY_SUPPLY_DOMESTIC_HOT_WATER_TOTAL';
    case EHEATER_ENERGY_CONSUMPTION_TOTAL = 'EHEATER_ENERGY_CONSUMPTION_TOTAL';

    case OUTDOOR_TEMPERATURE_MAX = 'OUTDOOR_TEMPERATURE_MAX';
    case OUTDOOR_TEMPERATURE_MEAN = 'OUTDOOR_TEMPERATURE_MEAN';
    case OUTDOOR_TEMPERATURE_MIN = 'OUTDOOR_TEMPERATURE_MIN';

    case NOT_NORMALIZED = 'NOT_NORMALIZED';
}
