<?php

namespace Elva\Common\Lib\Enums\Asset\NormalizedDeviceData;

use Elva\Common\Lib\Enums\Traits\Arrayable;

enum DataParameter: string
{
    use Arrayable;

    case DESIGN_OUTDOOR_TEMPERATURE = 'DESIGN_OUTDOOR_TEMPERATURE';
    case OUTDOOR_TEMPERATURE = 'OUTDOOR_TEMPERATURE';
    case HC_SUPPLY_TEMPERATURE = 'HC_SUPPLY_TEMPERATURE';
    case HC_ACTUAL_SUPPLY_TEMPERATURE = 'HC_ACTUAL_SUPPLY_TEMPERATURE';
    case HC_RETURN_TEMPERATURE = 'HC_RETURN_TEMPERATURE';

    case HC_ROOM_TEMPERATURE = 'HC_ROOM_TEMPERATURE';
    case HC_TARGET_ROOM_TEMPERATURE = 'HC_TARGET_ROOM_TEMPERATURE';

    case HC_TEMPERATURE_OFFSET = 'HC_TEMPERATURE_OFFSET';
    case HC_HEAT_CURVE_SLOPE = 'HC_HEAT_CURVE_SLOPE';
    case HC_ROOM_INFLUENCE = 'HC_ROOM_INFLUENCE';
    case HC_HEAT_CURVE = 'HC_HEAT_CURVE';
    case HC_ACTIVE = 'HC_ACTIVE';
    case HC_OPERATING_MODE = 'HC_OPERATING_MODE';
    case HC_ACTUAL_MODULATION = 'HC_ACTUAL_MODULATION';
    case HC_MODULATION_SET_POINT = 'HC_MODULATION_SET_POINT';

    case DHW_ACTUAL_TEMPERATURE = 'DHW_ACTUAL_TEMPERATURE';
    case DHW_TARGET_TEMPERATURE = 'DHW_TARGET_TEMPERATURE';
    case DHW_OPERATION_MODE = 'DHW_OPERATION_MODE';

    case DHW_ACTIVE = 'DHW_ACTIVE';

    case TOTAL_ELECTRICITY_CONSUMPTION = 'TOTAL_ELECTRICITY_CONSUMPTION';
    case TOTAL_ELECTRICITY_CONSUMPTION_LOW_RESOLUTION = 'TOTAL_ELECTRICITY_CONSUMPTION_LOW_RESOLUTION';
    case HC_ELECTRICITY_CONSUMPTION = 'COMPRESSOR_ELECTRICITY_CONSUMPTION';
    case HC_ELECTRICITY_CONSUMPTION_LOW_RESOLUTION = 'COMPRESSOR_ELECTRICITY_CONSUMPTION_LOW_RESOLUTION';
    case DHW_ELECTRICITY_CONSUMPTION = 'DHW_ELECTRICITY_CONSUMPTION';
    case DHW_ELECTRICITY_CONSUMPTION_LOW_RESOLUTION = 'DHW_ELECTRICITY_CONSUMPTION_LOW_RESOLUTION';
    case COOLING_ELECTRICITY_CONSUMPTION = 'COOLING_ELECTRICITY_CONSUMPTION';
    case COOLING_ELECTRICITY_CONSUMPTION_LOW_RESOLUTION = 'COOLING_ELECTRICITY_CONSUMPTION_LOW_RESOLUTION';

    case EHEATER_DHW_ELECTRICITY_CONSUMPTION = 'EHEATER_DHW_ELECTRICITY_CONSUMPTION';
    case EHEATER_DHW_ELECTRICITY_CONSUMPTION_LOW_RESOLUTION = 'EHEATER_DHW_ELECTRICITY_CONSUMPTION_LOW_RESOLUTION';
    case EHEATER_HEATING_ELECTRICITY_CONSUMPTION = 'EHEATER_HEATING_ELECTRICITY_CONSUMPTION';
    case EHEATER_HEATING_ELECTRICITY_CONSUMPTION_LOW_RESOLUTION = 'EHEATER_HEATING_ELECTRICITY_CONSUMPTION_LOW_RESOLUTION';
    case EHEATER_TOTAL_ELECTRICITY_CONSUMPTION = 'EHEATER_TOTAL_ELECTRICITY_CONSUMPTION';
    case EHEATER_TOTAL_ELECTRICITY_CONSUMPTION_LOW_RESOLUTION = 'EHEATER_TOTAL_ELECTRICITY_CONSUMPTION_LOW_RESOLUTION';

    case HC_ENERGY_OUTPUT = 'HC_ENERGY_OUTPUT';
    case DHW_ENERGY_OUTPUT = 'DHW_ENERGY_OUTPUT';
    case TOTAL_ENERGY_OUTPUT = 'TOTAL_ENERGY_OUTPUT';

    case COMPRESSOR_POWER_CURRENT = 'COMPRESSOR_POWER_CURRENT';
    case EHEATER_POWER_CURRENT = 'EHEATER_POWER_CURRENT';

    case OPERATING_CONDITION = 'OPERATING_CONDITION';

    case COMPRESSOR_OPERATION_STATUS = 'COMPRESSOR_OPERATION_STATUS';
    case EHEATER_OPERATION_STATUS = 'EHEATER_OPERATION_STATUS';

    case NOT_NORMALIZED = 'NOT_NORMALIZED';
}
