<?php

namespace Elva\Common\Lib\Enums\Asset\NormalizedDeviceData;

use Elva\Common\Lib\Enums\Traits\Arrayable;

enum DataParameter: string
{
    use Arrayable;

    case DESIGN_OUTDOOR_TEMPERATURE = 'DESIGN_OUTDOOR_TEMPERATURE';
    case OUTDOOR_TEMPERATURE = 'OUTDOOR_TEMPERATURE';
    case HC_SUPPLY_TEMPERATURE = 'HC_SUPPLY_TEMPERATURE';
    case HC_ACTUAL_SUPPLY_TEMPERATURE = 'HC_ACTUAL_SUPPLY_TEMPERATURE';
    case HC_RETURN_TEMPERATURE = 'HC_RETURN_TEMPERATURE';

    case HC_ROOM_TEMPERATURE = 'HC_ROOM_TEMPERATURE';
    case HC_TARGET_ROOM_TEMPERATURE = 'HC_TARGET_ROOM_TEMPERATURE';

    case HC_TEMPERATURE_OFFSET = 'HC_TEMPERATURE_OFFSET';
    case HC_HEAT_CURVE_SLOPE = 'HC_HEAT_CURVE_SLOPE';
    case HC_ROOM_INFLUENCE = 'HC_ROOM_INFLUENCE';
    case HC_HEAT_CURVE = 'HC_HEAT_CURVE';
    case HC_ACTIVE = 'HC_ACTIVE';
    case HC_OPERATING_MODE = 'HC_OPERATING_MODE';
    case HC_ACTUAL_POWER = 'HC_ACTUAL_POWER';
    case HC_POWER_SET_POINT = 'HC_POWER_SET_POINT';

    case DHW_ACTUAL_TEMPERATURE = 'DHW_ACTUAL_TEMPERATURE';
    case DHW_TARGET_TEMPERATURE = 'DHW_TARGET_TEMPERATURE';
    case DHW_OPERATION_MODE = 'DHW_OPERATION_MODE';

    case DHW_ACTIVE = 'DHW_ACTIVE';

    case ELECTRICITY_CONSUMPTION = 'ELECTRICITY_CONSUMPTION';
    case OPERATING_CONDITION = 'OPERATING_CONDITION';


    case NOT_NORMALIZED = 'NOT_NORMALIZED';
}
